-- Set up a test schema for storing sample data (optional)
CREATE SCHEMA IF NOT EXISTS TPCH_TEST;

-- Drop test tables if they exist (to ensure the script can be rerun)
DROP TABLE IF EXISTS TPCH_TEST.CUSTOMER_SAMPLE;
DROP TABLE IF EXISTS TPCH_TEST.ORDERS_SAMPLE;
DROP TABLE IF EXISTS TPCH_TEST.LINEITEM_SAMPLE;

-- Create test tables
CREATE TABLE TPCH_TEST.CUSTOMER_SAMPLE AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER
LIMIT 10;

CREATE TABLE TPCH_TEST.ORDERS_SAMPLE AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS
LIMIT 10;

CREATE TABLE TPCH_TEST.LINEITEM_SAMPLE AS
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM
LIMIT 10;

-- Verify sample data
SELECT COUNT(*) FROM TPCH_TEST.CUSTOMER_SAMPLE;
SELECT COUNT(*) FROM TPCH_TEST.ORDERS_SAMPLE;
SELECT COUNT(*) FROM TPCH_TEST.LINEITEM_SAMPLE;
